export const IPC = {
  PRODUCTS: {
    GET_ALL:        'products:getAll',
    GET_BY_ID:      'products:getById',
    GET_BY_BARCODE: 'products:getByBarcode',
    SEARCH:         'products:search',
    CREATE:         'products:create',
    UPDATE:         'products:update',
    DELETE:         'products:delete',
    BULK_PRICES:    'products:bulkPrices',
    BULK_NAMES:     'products:bulkNames',
    BULK_BARCODES:  'products:bulkBarcodes',
    BULK_COSTS:     'products:bulkCosts',
    SAVE_IMAGE:     'products:saveImage',
    IMPORT_BATCH:   'products:importBatch',
  },
  CATEGORIES: {
    GET_ALL:        'categories:getAll',
    CREATE:         'categories:create',
    UPDATE:         'categories:update',
    DELETE:         'categories:delete',
    REORDER:        'categories:reorder',
  },
  VARIATIONS: {
    GET_GROUPS:     'variations:getGroups',
    CREATE_GROUP:   'variations:createGroup',
    UPDATE_GROUP:   'variations:updateGroup',
    DELETE_GROUP:   'variations:deleteGroup',
    ADD_OPTION:     'variations:addOption',
    UPDATE_OPTION:  'variations:updateOption',
    DELETE_OPTION:  'variations:deleteOption',
  },
  ORDERS: {
    CREATE:                   'orders:create',
    GET_ALL:                  'orders:getAll',
    GET_BY_ID:                'orders:getById',
    UPDATE_STATUS:            'orders:updateStatus',
    EXCLUDE_SALES:            'orders:excludeSales',
    REFUND:                   'orders:refund',
    PARTIAL_REFUND:           'orders:partialRefund',
    SAVE_CART:                'orders:saveCart',
    GET_SAVED:                'orders:getSaved',
    DELETE_SAVED:             'orders:deleteSaved',
    GET_PENDING:              'orders:getPending',
    GET_CASHIER_SALES_TODAY:  'orders:getCashierSalesToday',
  },
  INVENTORY: {
    GET_ALL:        'inventory:getAll',
    ADD_STOCK:      'inventory:addStock',
    SET_STOCK:      'inventory:setStock',
    GET_MOVEMENTS:  'inventory:getMovements',
    SET_THRESHOLD:  'inventory:setThreshold',
  },
  DEBTORS: {
    GET_ALL:        'debtors:getAll',
    GET_BY_ID:      'debtors:getById',
    CREATE:         'debtors:create',
    UPDATE:         'debtors:update',
    DELETE:         'debtors:delete',
    ADD_TRANSACTION:'debtors:addTransaction',
    GET_TRANSACTIONS:'debtors:getTransactions',
    MARK_REMINDER:  'debtors:markReminder',
  },
  ANALYTICS: {
    GET_DASHBOARD:  'analytics:getDashboard',
    GET_REPORT:     'analytics:getReport',
    GET_DAILY:      'analytics:getDaily',
    GET_CASHFLOW:   'analytics:getCashflow',
    GET_HOURLY:     'analytics:getHourly',
    GET_TOP_PRODUCTS:'analytics:getTopProducts',
    GET_CATEGORIES: 'analytics:getCategories',
    GET_FINANCIALS: 'analytics:getFinancials',
    GET_TOP_DEBTORS:'analytics:getTopDebtors',
    GET_SLOW_MOVING:'analytics:getSlowMoving',
    GET_PAYMENT_BREAKDOWN: 'analytics:getPaymentBreakdown',
  },
  PRICE_TIERS: {
    GET:    'priceTiers:get',
    SET:    'priceTiers:set',
    DELETE: 'priceTiers:delete',
  },
  SHIFTS: {
    TIME_IN:        'shifts:timeIn',
    TIME_OUT:       'shifts:timeOut',
    GET_ACTIVE:     'shifts:getActive',
    GET_ALL:        'shifts:getAll',
    ADD_PETTY_CASH: 'shifts:addPettyCash',
    GET_PETTY_CASH: 'shifts:getPettyCash',
  },
  EXPENSES: {
    GET_ALL:     'expenses:getAll',
    CREATE:      'expenses:create',
    UPDATE:      'expenses:update',
    DELETE:      'expenses:delete',
    GET_SUMMARY: 'expenses:getSummary',
  },
  SETTINGS: {
    GET_ALL:        'settings:getAll',
    GET:            'settings:get',
    SET:            'settings:set',
    SET_MANY:       'settings:setMany',
  },
  AUTH: {
    LOGIN:          'auth:login',
    LOGOUT:         'auth:logout',
    CLOUD_LOGOUT:   'auth:cloudLogout',
    GET_USERS:      'auth:getUsers',
    CREATE_USER:    'auth:createUser',
    UPDATE_USER:    'auth:updateUser',
    SIGNUP:         'auth:signup',
    CLOUD_LOGIN:    'auth:cloudLogin',
    SYNC_CASHIERS:  'auth:syncCashiers',
  },
  PRINTER: {
    PRINT_RECEIPT:  'printer:printReceipt',
    TEST_PAGE:      'printer:testPage',
    GET_STATUS:     'printer:getStatus',
    SET_CONFIG:     'printer:setConfig',
    OPEN_DRAWER:    'printer:openDrawer',
    LIST_PRINTERS:  'printer:listPrinters',
  },
  SYNC: {
    GET_STATUS:     'sync:getStatus',
    FORCE:          'sync:force',
    TRIGGER_AUTO:   'sync:triggerAuto',
  },
  BACKUP: {
    EXPORT:         'backup:export',
    IMPORT:         'backup:import',
    RESET:          'backup:reset',
  },
  ACTIVATION: {
    GET_INSTALL_ID:  'activation:getInstallId',
    GET_STATUS:      'activation:getStatus',
    CREATE_INVOICE:  'activation:createInvoice',
    CHECK_STATUS:    'activation:checkStatus',
    MARK_ACTIVATED:  'activation:markActivated',
  },
  SMS: {
    SEND:        'sms:send',
    GET_CREDITS: 'sms:getCredits',
    GET_LOG:     'sms:getLog',
  },
  LOYALTY: {
    GET_ALL:       'loyalty:getAll',
    GET_BY_PHONE:  'loyalty:getByPhone',
    CREATE:        'loyalty:create',
    EARN:          'loyalty:earn',
    REDEEM:        'loyalty:redeem',
    ADJUST:        'loyalty:adjust',
    GET_HISTORY:   'loyalty:getHistory',
    DELETE:        'loyalty:delete',
  },
  // Push events: main → renderer
  PUSH: {
    BARCODE_SCANNED:'push:barcodeScanned',
    SYNC_STATUS:    'push:syncStatus',
    NEW_ORDER:      'push:newOrder',
  },
} as const
